on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select deployment environment"
        required: true
        type: choice
        options:
          - nonprod
          - prod
      tenant_name:
        description: "Select the tenant name"
        required: true
        type: choice
        options:
          - demo
          - demo1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Check selected environment
        run: echo "Selected environment:${{ github.event.inputs.environment }}"

      - name: Set up Deployment for nonprod
        if: ${{ github.event.inputs.environment == 'nonprod' }}
        run: |
          echo "Deploying to nonprod environment"
          # message=$(yq eval '.message' tenants/demo/nonprod/configs.yml)
          cat tenants/demo/${{  github.event.inputs.environment  }}/configs.yml
          echo "Message from nonprod config: $message"
          # Add your nonprod deployment commands here

      - name: Set up Deployment for prod
        if: ${{ github.event.inputs.environment == 'prod' }}
        run: |
          echo "Deploying to prod environment"
          message=$(yq eval '.message' tenants/demo/prod/config.yml)
          echo "Message from prod config: $message"
          # Add your prod deployment commands here        
