on:
  workflow_dispatch:
    inputs:
      tenant:
        description: "Select the tenant name"
        required: true
        type: choice
        options:
          - demo
          - demo1
      environment:
        description: "Select deployment environment"
        required: true
        type: choice
        options:
          - nonprod
          - prod


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Check selected environment
        run: |
         echo "Selected tenant:${{ inputs.tenant }}"
         echo "Selected environment:${{ inputs.environment }}"

      - name: Set up Deployment for nonprod
      
        run: |
          echo "Deploying to selected tenants and environment"
          cat tenants/${{  inputs.tenant  }}/${{  inputs.environment  }}/config.yml

      # - name: Set up Deployment for prod
      #   if: ${{ github.event.inputs.environment == 'prod' }}
      #   run: |
      #     echo "Deploying to prod environment"
      #     cat tenants/${{  inputs.tenant  }}/${{  inputs.environment  }}/config.yml
     
